# Generated by Django 6.0.2 on 2026-02-20 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='내용')),
                ('image', models.ImageField(blank=True, upload_to='post_images/', verbose_name='이미지')),
                ('thumbnail', models.ImageField(blank=True, upload_to='post_thumbnails/', verbose_name='썸네일')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '게시물',
                'verbose_name_plural': '게시물',
                'ordering': ['-created_at'],
            },
        ),
    ]
